### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by flamergamer1234** [Electromaster232/Discord-LiveBot#1]
- [ ] Embedded images show in app

- [ ] Markdown

- [ ] Clickable links

- [ ] Emojis

**Comment by flamergamer1234** [comment]
- [ ] Uncomment settings icon, put in right place and make it work
![image](https://user-images.githubusercontent.com/31465218/43174225-e98c4f08-8f86-11e8-9a7f-e3d419004840.png)

**Comment by flamergamer1234** [comment]
- [ ] Add Direct Message support

**Comment by RossMdevs** [comment]
I’ve added two labels onto this: Feature Request and Needs Done!

**Comment by flamergamer1234** [comment]
I meant #5 on that last commit

**Comment by RossMdevs** [comment]
## Added Installer 
- [ ] Installer

**Comment by RossMdevs** [comment]
## Moderation Functionality 
- [ ] Ability to KICK/BAN **Bot/User**
- [ ] Ability to open Server settings and access Audit Logs, Bans, Roles Misc. **User Only**
- [ ] Ability to move channels **User Only**

**Comment by RossMdevs** [comment]
## **CRITICAL**
- [ ] Ratelimiting
